### ISSUE TITLE
Babelfish compass generate different results for the same database DDL script just with a different encoding

### ISSUE THREAD

**Issue by yoni-yad2** [babelfish-for-postgresql/babelfish_compass#104]
Ran BabelfishCompass.bat to generate a report against a DDL script generated by SSMS (Right click on DB->"Tasks"->"Generate scripts") which uses a UTF-16 encoding.

Then I saved the DDL script to as a new script with a UTF-8 encoding with Notepad++
and compared both scripts using Notepad++ compare plugin which didn't find any differences.

But when I ran BabelfishCompass.bat again against the UTF-8 script I got **smaller** numbers (in the hundreds) in the second report for:

Assessment Summary

#lines SQL in objects
total #SQL features
Supported
Not Supported
Review Semantics
Automatic SQL rewrite opportunities

Object Count

PROCEDURE

**Comment by rcv-aws** [comment]
Weird. Is it possible for you to send both scripts (at least a small part of both that shows the problem) to rcv-at-amazon-dot-com?

**Comment by yoni-yad2** [comment]
Can you please first try following the steps I did on your env and see if you can recreate this issue?

**Comment by rcv-aws** [comment]
I replayed the steps you describe, and I get exactly the same Compass reports. I even took 2 UTF8 copies: one with BOM and one without (Notepad++ offers those options), but it made no difference. So in summary, I cannot reproduce your issue myself.
