### ISSUE TITLE
Babelfish Compass Assessment error: Cannot generate report based on these analysis files with incompatible attributes

### ISSUE THREAD

**Issue by yoni-yad2** [babelfish-for-postgresql/babelfish_compass#112]
### What happened?

I ran this command:

`.\BabelfishCompass.bat PostgresMigrationAssessmentReport C:\temp\db.sql -replace`

Got:

Babelfish Compass v.2023-06, June 2023
Compatibility assessment tool for Babelfish for PostgreSQL
Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

Run starting               : 09-Aug-2023 10:16:21 (Windows)
BabelfishFeatures.cfg file : v.3.2.0, Jun-2023
Target Babelfish version   : v.3.2.0 (PG 15.3)
.....
.....
.....
**Cannot generate report based on these analysis files with incompatible attributes.
Analysis was performed for a different Babelfish version (v.) than targeted by this run (v.3.2.0):

Re-run analysis for all imported files with -analyze, or specify
the corresponding Babelfish version with -babelfish-version.**

### Version

BABEL_3_X_DEV (Default)

### Extension

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by robverschoor** [comment]
Are you , by any chance, using a Chinese locale ? And therefore having a date notation that uses CN characters for the month? Can you please look at https://github.com/babelfish-for-postgresql/babelfish_compass/issues/111 and see if it is the same issue?

**Comment by yoni-yad2** [comment]
I use a Hebrew locale.

header of dat file:

# Captured items for report [PostgresMigrationAssessmentReport] with targeted Babelfishversion [3.2.0] generated at 09-**אוג**-2023 16:47:53 with capture file format [1] user config file [BabelfishCompassUser.cfg]

**Comment by yoni-yad2** [comment]
Update: Issue doesn't happen when date is in US format.

**Comment by robverschoor** [comment]
Thanks, this is indeed the same issue as https://github.com/babelfish-for-postgresql/babelfish_compass/issues/111 . A fix will be in the next Compass release.

**Comment by robverschoor** [comment]
This has been fixed in Compass v.2023-08
