### ISSUE TITLE
maven-assembly-plugin configuration errors in POM

### ISSUE THREAD

**Issue by brtrvn** [babelfish-for-postgresql/babelfish_compass#13]
The `<configuration>` tag for the maven-assembly-plugin does not use `<source>` or `<target>` like the maven-compiler-plugin does.

**Comment by hsuamz** [comment]
@brtrvn : Thanks for submitting the change. To confirm, would you be OK if we closed this issue? Thanks.

**Comment by brtrvn** [comment]
Absolutely!

What we've been doing in our repo is "linking" PRs and Issues which automagically closes issues when the resolving PR is merged into main. It also automatically adds "mentioned" comments in the PR and the Issue so you can easily see the connection.
