### ISSUE TITLE
Emoji not rendered correctly on MacOs

### ISSUE THREAD

**Issue by rcv-aws** [babelfish-for-postgresql/babelfish_compass#44]
The Babelfish Compass reports generate some lines which start with an emoji to indicate the line has a cursor pop-up with additional information. The emoji is [http://www.unicode-symbol.com/u/1F6C8.html](http://www.unicode-symbol.com/u/1F6C8.html) and on Windows it renders correctly in Firefox, Edge and Chrome, it looks like this:
![image](https://user-images.githubusercontent.com/91290800/149765269-5ba5a6a2-faf7-4d6b-9a95-4631be3c5b5c.png)

However, there have been cases where on MacOS the emoji is rendered incorrectly in Safari and Firefox, looking like a square with hexadecimal digits inside, like this:
![image](https://user-images.githubusercontent.com/91290800/149764699-6c3a45d3-8280-4258-b683-3cf6225f4885.png)

However, there have also been reports that the emoji is rendered correctly in MacOS Safari. 

In order to get to the bottom of this, a developer with MacOS is invited to participate in this.

**Comment by laurenz** [comment]
I am certainly not a MacOS expert, but this looks like the character is recognized correctly, but some fonts are missing.

**Comment by brtrvn** [comment]
What about using this symbol/emoji instead?

http://www.unicode-symbol.com/u/2139.html
https://unicode-table.com/en/2139/

Just did a quick test on Mac and Windows 2019 and it renders correctly on both. I can create a PR.

Note that there are other emojis/symbols that also don't render properly on Mac (haven't tried Linux yet). For example, the "book" icon `&#x1F56E;` is another that we would need to find a replacement for.

**Comment by rcv-aws** [comment]
This has been fixed in Compass version 2022-02, using a different emoji which appears to render OK on MacOS
