### ISSUE TITLE
Jar file execution error

### ISSUE THREAD

**Issue by elangodba** [babelfish-for-postgresql/babelfish_compass#73]
Hi Team,

Am trying to execute bablefishcompass but i encounter the below error.

Error: Unable to access jarfile compass.jar

i could not find the jar file the downloaded package. Kindly help

**Comment by rcv-aws** [comment]
Download the .zip file from https://github.com/babelfish-for-postgresql/babelfish_compass/releases/tag/v2022-03-a . Inside the .zip file is a directory named **BabelfishCompass**. You need to run Compass from within this directory by invoking **BabelfishCompass.bat** or **BabelfishCompass.sh**, depending on your O/S. The compass.jar file is located in the same directory.
You cannot run the Compass tool from a different directory as it won't find the .jar file (unless you modify the classpath yourself).
